FROM ansible/centos7-ansible
MAINTAINER Victor Martinez "VictorMartinezRubio+ansible@gmail.com"
RUN yum install -y \
  unzip tar && yum clean all
VOLUME ["/playbook"]
ENV ANSIBLE_FORCE_COLOR true
ENV PYTHONUNBUFFERED 1
CMD cd /playbook/tests && ansible-playbook -i inventory.docker site.ci.yml -c local -T 2 -vv
