FROM ubuntu:14.04
MAINTAINER Victor Martinez "VictorMartinezRubio+ansible@gmail.com"
RUN apt-get -y update \
    && apt-get install -y software-properties-common \
    && apt-add-repository ppa:ansible/ansible \
    && apt-get -y update \
    && apt-get install -y python-yaml python-jinja2 ansible
VOLUME ["/playbook"]
ENV ANSIBLE_FORCE_COLOR true
ENV PYTHONUNBUFFERED 1
CMD cd /playbook/tests && ansible-playbook -i /playbook/tests/docker.inventory /playbook/tests/test.yml -c local -T 2 -vv
