FROM debian:wheezy
MAINTAINER Victor Martinez "VictorMartinezRubio+ansible@gmail.com"
RUN apt-get -y update \
    && apt-get install -y python-yaml python-jinja2 python-pip  python-dev
RUN pip install ansible
VOLUME ["/playbook"]
ENV ANSIBLE_FORCE_COLOR true
ENV PYTHONUNBUFFERED 1
CMD cd /playbook/tests && ansible-playbook -i inventory.docker site.ci.yml -c local -T 2 -vv
