BOX_NAME = ENV['VAGRANT_BOX_NAME'] || 'XXXXXXX/XXXXX'

Vagrant.configure('2') do |config|
  config.vm.box = BOX_NAME
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'test.yml'
    ansible.limit = 'all'
    ansible.sudo = true
    ansible.host_key_checking = false
  end

  config.vm.define 'chef-client' do |c|
    c.vm.host_name = 'chef-client'
  end
end
